### ISSUE TITLE
Mention sending data before a response

### ISSUE THREAD

**Issue by tfpauly** [bemasc/modern-http-proxies#1]
Like CONNECT-UDP, we should explicitly mention that the client is allowed to send data prior to receiving the response, so we can send info like the TLS client hello.

Currently CONNECT proxying leaves this ambiguous, and support amongst servers is inconsistent.

**Comment by bemasc** [comment]
OK, please review a proposed fix: #2.

In the course of writing this up, I realized that HTTP/1.1 and HTTP/2 are actually very different here.  The current proposed text only allows this in HTTP/2 and HTTP/3.

I also threw in some other setup-related improvements just for fun.
